apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateful-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stateful-demo
  template:
    metadata:
      labels:
        app: stateful-demo
    spec:
      containers:
        - name: nginx
          image: nginx
